package com.example.beatpulse.utils

val desktopStringsEs = mapOf(
    "app_name" to """DuWave""",
    "perm_mic_denied" to """Las animaciones rítmicas están desactivadas porque no hay permiso de micrófono.""",
    "perm_storage_denied" to """Se requiere permiso de almacenamiento para buscar tu música.""",
    "add_to_playlist" to """Añadir a Playlist""",
    "no_playlists" to """No tienes playlists creadas. Crea una desde la pestaña de Álbumes.""",
    "added_to_playlist" to """Añadida a %1${'$'}s""",
    "close" to """Cerrar""",
    "welcome_title" to """¡Bienvenido a DuWave!""",
    "welcome_body" to """👋 Gestos Principales:\n\n• Desliza a los lados en el mini-reproductor para cambiar entre Inicio, Biblioteca y Reproductor.\n\n• Usa la lupa en Biblioteca para buscar y el botón de recargar para buscar música nueva.\n\n• Toca aquí para comenzar a escuchar.""",
    "tab_all" to """Todos""",
    "tab_browser" to """Navegador""",
    "tab_recommendations" to """Recomendaciones""",
    "reload_local_music" to """Recargar música local""",
    "search_local_music" to """Buscar música local...""",
    "search_recommendation" to """Buscar recomendación (ej: artista)""",
    "today_recommendations" to """Recomendaciones de hoy""",
    "recommendations_desc" to """Explora y descubre música que podría gustarte basada en tus más escuchadas.""",
    "track_deleted" to """Canción eliminada""",
    "delete_from_library" to """Eliminar de la biblioteca""",
    "more_options" to """Más opciones""",
    "my_playlists" to """Mis Playlists""",
    "other_local_folders" to """Otras carpetas locales""",
    "tap_plus_to_add" to """Toca el botón + para añadir una lista.""",
    "no_tracks_found" to """No se encontraron canciones.""",
    "delete" to """Eliminar""",
    "no_folders_found" to """No se encontraron carpetas con música.""",
    "select_language" to """Selecciona Idioma""",
    "language" to """Idioma""",
    "tab_albums" to """Álbumes""",
    "tab_playlists" to """Playlists""",
    "tab_folders" to """Carpetas""",
    "create_playlist" to """Crear Playlist""",
    "playlist_name" to """Nombre de la Playlist""",
    "create" to """Crear""",
    "visualizer_style" to """Estilo de Visualizador""",
    "visualizer_bg" to """Fondo Dinámico""",
    "visualizer_sensitivity" to """Sensibilidad Visual""",
    "visualizer_mode" to """Modo de Ondas""",
    "mode_3_band" to """Separadas (Altos, Medios, Bajos)""",
    "mode_1_band" to """Unificada (Todo en uno)""",
    "library" to """Biblioteca""",
    "searching_music" to """Buscando música...""",
    "searching_recs" to """Buscando recomendaciones basadas en tus estadísticas...""",
    "no_tracks_here" to """No hay canciones aquí.""",
    "no_results_online" to """No se encontraron resultados online.""",
    "refresh_recommendations" to """Actualizando pronto...""",
    "sort_directory" to """Directorio por defecto""",
    "sort_title" to """Título A-Z""",
    "sort_artist" to """Artista A-Z""",
    "sort_album" to """Álbum A-Z""",
    "next_update_in_h_m" to """Próxima actualización en %1${'$'}dh %2${'$'}dm""",
    "updating_soon" to """Actualizando pronto...""",
    "because_you_listened" to """Porque escuchaste a %1${'$'}s""",
    "top_artists" to """Top Artistas""",
    "trending_music" to """Música de moda""",
    "artist_based_on" to """Artista basado en la canción""",
    "show_whatsapp_audio" to """Mostrar audios WhatsApp""",
    "hide_whatsapp_audio" to """Ocultar audios WhatsApp""",
    "scan_music_now" to """Escanear música ahora""",
    "shape_squiggle" to """Forma squiggle""",
    "shape_square" to """Forma cuadrada""",
    "shape_circle" to """Forma circular""",
    "shape_rounded" to """Forma redondeada""",
    "shape_prefix" to """Forma: """,
    "style_prefix" to """Estilo: """,
    "style_bars" to """Barras""",
    "style_circle" to """Círculo""",
    "style_ring" to """Anillo""",
    "style_waves" to """Ondas""",
    "style_slime" to """Slime""",
    "style_bands" to """Bandas""",
    "style_dots" to """Puntos""",
    "style_particles" to """Partículas""",
    "style_rings" to """Anillos""",
    "style_aura" to """Aura""",
    "style_duwave" to """DuWave""",
    "tab_artists" to """Artistas""",
    "playback_settings" to """Ajustes de Reproducción""",
    "edit_tag" to """Editar Etiqueta""",
    "eq_normal" to """Normal""",
    "eq_reverb" to """Reverberación""",
    "eq_activate" to """activar""",
    "eq_deactivate" to """desactivar""",
    "equalizer" to """Ecualizador""",
    "suggest_github" to """Sugerir mejoras en GitHub""",
    "delete_from_device" to """Eliminar del dispositivo""",
    "general_lists" to """Listas Generales""",
    "my_lists" to """Mis Listas""",
    "shuffle_playback" to """Reproducción Aleatoria""",
    "repeat_method" to """Método de Repetición""",
    "visualizer_style_opt" to """Estilo de Visualización""",
    "visualizer_physics" to """Física del Visualizador""",
    "bands_mode" to """Modo de bandas""",
    "speed_and_pitch" to """Velocidad y tono""",
    "speed_format" to """Velocidad: %1${'$'}sx""",
    "pitch_format" to """Tono: %1${'$'}sx""",
    "title" to """Título""",
    "artist" to """Artista""",
    "album" to """Álbum""",
    "save" to """Guardar""",
    "cancel" to """Cancelar""",
    "enable_equalizer" to """Activar ecualizador""",
    "custom" to """Personalizado""",
    "your_statistics" to """Tus Estadísticas""",
    "start_listening_stats" to """Empieza a escuchar música para ver tus estadísticas aquí.""",
    "searching_recommendations" to """Buscando recomendaciones basadas en tus estadísticas...""",
    "searching_online" to """Buscando online...""",
    "search_lyrics" to """Letras""",
    "off" to """Desactivado""",
    "repeat_list" to """Lista""",
    "repeat_one" to """Una""",
    "repeat_ab" to """A y B""",
    "wave_archetype" to """Arquetipo de Ondas""",
    "waves_3_overlapping" to """3 Ondas Superpuestas""",
    "wave_1_combined" to """1 Onda Combinada""",
    "calculation_mode_fft" to """Modo de Cálculo (FFT)""",
    "fft_average" to """Promedio (Estable)""",
    "fft_maximum" to """Máximo (Dinámico)""",
    "chaos_reactivity_format" to """Reactividad de Caos: %1${'$'}sx""",
    "bass_sensitivity_format" to """Sensibilidad de Graves (Bajos): %1${'$'}sx""",
    "mid_sensitivity_format" to """Sensibilidad de Medios: %1${'$'}sx""",
    "treble_sensitivity_format" to """Sensibilidad de Altos (Agudos): %1${'$'}sx""",
    "general_sensitivity_format" to """Sensibilidad General: %1${'$'}sx""",
    "advanced_sensitivity" to """Sensibilidad Avanzada""",
    "choose_cover" to """Elegir Portada""",
    "custom_cover_selected" to """Portada personalizada seleccionada""",
    "audio_effects" to """Efectos de Audio""",
    "preset_effects" to """Preajuste (Efectos)""",
    "slow_reverb" to """Slow Reverb""",
    "auto_mode_loudness" to """Modo Auto (Loudness)""",
    "preset_label" to """Preset:""",
    "sleep_timer" to """Temporizador""",
    "exact_timer" to """Temporizador Exacto""",
    "turn_off" to """Apagar""",
    "suggest_improvements" to """Sugerir mejoras""",
    "suggest_improvements_desc" to """¿Deseas abrir el navegador para sugerir mejoras o reportar problemas en GitHub?""",
    "playback_queue" to """Cola de Reproducción""",
    "accept" to """Aceptar""",
    "open" to """Abrir""",
    "no_playlists_long" to """No tienes playlists creadas. Crea una desde la pestaña de Álbumes.""",
    "no_playlists_short" to """No tienes playlists creadas.""",
    "new_playlist" to """Nueva Playlist""",
    "search_songs" to """Buscar canciones...""",
    "add_songs" to """Añadir Canciones""",
    "search_in_format" to """Buscar en %1${'$'}s...""",
    "delete_song_title" to """Eliminar canción""",
    "delete_song_desc" to """¿Estás seguro de que quieres eliminar permanentemente \'%1${'$'}s\' del dispositivo?""",
    "confirm_download" to """Confirmar descarga""",
    "confirm_download_desc" to """¿Deseas descargar \'%1${'$'}s\' a tu dispositivo para escucharla sin conexión?""",
    "download" to """Descargar""",
    "remove_from_playlist" to """Quitar de la Playlist""",
    "download_music" to """Descargar música""",
    "trim_audio" to """Recortar audio""",
    "save_trim" to """Guardar Recorte""",
    "start_time" to """Tiempo de inicio: %1${'$'}s""",
    "end_time" to """Tiempo de fin: %1${'$'}s""",
    "trimming_audio" to """Recortando audio...""",
    "trim_saved_success" to """Recorte guardado con éxito""",
    "trim_error" to """Error al recortar audio""",
    "playback_progress" to """Progreso: %1${'$'}s""",
    "confirm_link_download" to """Confirmar descarga de enlace""",
    "download_from_youtube_desc" to """¿Descargar \"%1${'$'}s\" de YouTube?""",
    "stats_title" to """Tus Estadísticas""",
    "stats_no_data" to """¡Aún no hay datos!""",
    "stats_you_listened" to """Has escuchado""",
    "stats_of_music" to """de música""",
    "stats_total_plays" to """%1${'$'}s reproducciones totales""",
    "stats_songs" to """Canciones""",
    "stats_artists" to """Artistas""",
    "stats_albums" to """Álbumes""",
    "stats_top_artists" to """Artistas Más Escuchados""",
    "stats_top_songs" to """Canciones Más Escuchadas""",
    "stats_top_albums" to """Álbumes Más Escuchados""",
    "stats_your_favorites" to """Tus Favoritas""",
    "stats_plays_short" to """%1${'$'}s rep.""",
    "based_on" to """Basado en: %1${'$'}s""",
    "for_you" to """Para ti""",
    "search_dots" to """Buscar...""",
    "search_online_dots" to """Buscar online...""",
    "shape_squircle" to """Forma: Squircle""",
    "change_cover_title" to """Cambiar Portada""",
    "style_classic" to """Estilo: Clásico""",
    "style_cyberpunk" to """Estilo: Cyberpunk""",
    "style_anime" to """Estilo: Anime Pastel""",
    "style_luminous" to """Estilo: Luminoso""",
    "style_kawaii" to """Estilo: Kawaii""",
    "style_black_metal" to """Estilo: Black Metal""",
    "style_dark_fantasy" to """Estilo: Dark Fantasy""",
    "style_cathedral" to """Estilo: Catedral""",
    "style_hearts" to """Estilo: Corazones""",
    "style_tale_legend" to """Estilo: Leyenda Cuento""",
    "reload_covers" to """Recargar Portadas""",
    "reloading_covers_progress" to """Recargando %1${'$'}d de %2${'$'}d...""",
    "covers_reloaded" to """Portadas recargadas""",
    "support_dialog_title" to """Apoyar y Sugerencias""",
    "support_ideas_title" to """¿Quieres aportar ideas?""",
    "support_ideas_desc" to """Escríbelo en las issues de GitHub para mejorar la aplicación.""",
    "support_patreon_title" to """Apoya el proyecto""",
    "support_patreon_desc" to """Para que siga creciendo con más estilos, más tipos de onda y beneficios personales.""",
    "gesture_next_prev" to """Toca dos veces los bordes para cambiar de canción""",
    "gesture_seek_10s" to """Toca dos veces aquí para adelantar o retrasar 10s""",
    "gesture_vinyl_seek" to """Gira la portada para adelantar o retrasar""",
    "gesture_playlist_swipe" to """Desliza hacia arriba para abrir la lista""",
    "gesture_confirmations_toggle" to """Confirmaciones visuales de gestos""",
    "download_completed" to """Descarga completada""",
    "download_completed_desc" to """Descarga completada: %1${'$'}s""",
    "player_options" to """Opciones del reproductor""",
    "basic_options" to """Opciones Básicas""",
    "advanced_options" to """Opciones Avanzadas""",
    "visuals" to """Aspecto Visual""",
    "dynamic_plus" to """Colores Dinámicos+""",
    "reset_defaults" to """Restablecer a valores por defecto""",
    "enable_equalizer" to """Activar ecualizador""",
    "auto_loudness" to """Modo Auto-Loudness""",
    "presets" to """Ajustes preestablecidos""",
    "preset_custom" to """Personalizado""",
    "normal" to """Normal""",
    "trim_audio_anchor" to """Ancla actual: %s""",
    "start_time" to """Inicio: %s""",
    "end_time" to """Fin: %s""",
    "trim_audio_start_btn" to """Inicio""",
    "trim_audio_play_anchor" to """Desde ancla""",
    "trim_audio_stop" to """Detener""",
    "trim_audio_minus_10s" to """-10s al fin""",
    "trim_audio_trim_btn" to """Recortar""",
    "trim_error_generic" to """Error al recortar audio.""",
    "checking_dependencies" to """Comprobando dependencias...""",
    "ffmpeg_required_desc" to """Se requiere FFmpeg.""",
    "downloading_ffmpeg" to """Descargando FFmpeg...""",
    "download_ffmpeg_btn" to """Descargar FFmpeg""",
    "duration_unknown_note" to """Duración desconocida.""",
    "search_in_category" to """Buscar en %s...""",
    "folders_category" to """Carpetas""",
    "no_playlists_created" to """No tienes playlists creadas. Crea una desde la pestaña de Álbumes.""",
    "delete_track_title" to """Eliminar canción""",
    "delete_track_desc" to """¿Estás seguro de que quieres eliminar permanentemente \'%1${'$'}s\' del dispositivo?""",
    "delete_button_red" to """Eliminar""",
    "play_trimmed" to """Reproducir Recorte""",
    "pause_trimmed" to """Pausar""",
    "stats_time_format" to """%1${'$'}d horas %2${'$'}d minutos""",
    "toast_fetching_link" to """Obteniendo enlace de %1${'$'}s...""",
    "toast_download_started" to """Descarga iniciada: %1${'$'}s""",
    "toast_download_failed_link" to """No se pudo obtener el enlace de %1${'$'}s""",
    "toast_download_error" to """Error al procesar descarga de %1${'$'}s""",
    "toast_downloading" to """Descargando %1${'$'}s...""",
    "all_songs_title" to """Todas las canciones""",
    "recent_plays_title" to """Reproducciones Recientes""",
    "favorites_title" to """Favoritos""",
    "top_plays_title" to """Mejores Reproducciones""",
    "recently_added_title" to """Últimos Agregados""",
    "playback_error" to """Error al reproducir: Archivo no encontrado o dañado.""",
    "online_service_down" to """El servicio no está disponible de momento, por favor, espera una nueva actualización.""",
    "swipe_to_choose" to """¡Desliza el minirreproductor a los lados para cambiar de sección!""",
    "shazam_api_unavailable" to """La API de reconocimiento musical no funciona actualmente. Espere a una próxima actualización.""",
    "shazam_mic_denied" to """Se necesita permiso de micrófono para reconocer la canción.""",
    "shazam_indie_warning" to """Funciona mejor con música comercial (Spotify, Apple). Los remixes o canciones de YouTube/Juegos podrían no ser reconocidos.""",
    "shazam_no_match" to """No se encontró ninguna coincidencia.""",
    "shazam_unknown_error" to """Error desconocido al escuchar.""",
    "shazam_listening_title" to """Escuchando...""",
    "shazam_listening_desc" to """Acerca el micrófono a la música. Déjelo sonar por unos segundos...""",
    "shazam_found_title" to """¡Canción encontrada!""",
    "shazam_search_button" to """Buscar Canción""",
    "shazam_error_title" to """No se pudo reconocer""",
    "shazam_retry_button" to """Reintentar""",
    "mic_test_title" to """Prueba de Audio en Vivo""",
    "mic_test_desc" to """Esta sección sirve para probar tu voz o el entorno en vivo con los visualizadores de DuWave. Requiere acceso al micrófono para sincronizar las ondas, pero no grabará ni guardará audio.""",
    "clean_ui" to """UI Limpia""",
    "move" to """Mover""",
    "effects" to """Efectos""",
    "normal" to """Normal""",
    "chroma" to """Croma""",
    "hidden" to """Oculta""",
    "select_custom_cover" to """Seleccionar imagen de portada personalizada""",
    "cover_size" to """Tamaño de la portada""",
    "exit_streamer_mode" to """Salir del modo Streamer""",
    "mic_bar" to """Barra micrófono""",
    "cover_options" to """Opciones de Portada""",
    "player_options" to """Opciones de Reproductor""",
    "basic_options" to """Básicos""",
    "advanced_options" to """Avanzados""",
    "visuals" to """Visuales""",
    "visual_waves" to """Ondas visuales""",
    "archetypes" to """Arquetipos""",
    "three_overlapping_waves" to """3 Ondas superpuestas""",
    "one_combined_wave" to """Una onda combinada""",
    "general_sensitivity" to """Sensibilidad General""",
    "fluidity" to """Fluidez""",
    "reactivity" to """Reactividad""",
    "visual_style" to """Estilo Visual""",
    "waves" to """Ondas""",
    "slime" to """Slime""",
    "bars" to """Barras""",
    "dots" to """Puntos""",
    "particles" to """Partículas""",
    "rings" to """Anillos""",
    "aura" to """Aura""",
    "bands" to """Bandas""",
    "terrain_3d" to """Terreno 3D""",
    "star" to """Estrella""",
    "oscilloscope" to """Osciloscopio""",
    "trap_nation" to """Trap Nation""",
    "perspective_bands" to """Bandas con perspectiva""",
    "archetype" to """Arquetipo""",
    "three_combined_waves" to """Tres ondas combinadas""",
    "frequency_sensitivity" to """Sensibilidad por frecuencia""",
    "advanced" to """Avanzado""",
    "bass" to """Bajos""",
    "mids_treble" to """Medios y Agudos""",
    "advanced_cover_options" to """Opciones avanzadas de portada""",
    "cover_mode" to """Modo de portada""",
    "size" to """Tamaño""",
    "cover_preview" to """Previsualización de la portada""",
    "generated_palette" to """Paleta generada""",
    "apply" to """Aplicar""",
    "listening" to """Escuchando...""",
    "could_not_recognize" to """No se pudo reconocer""",
    "no_match_found" to """No se encontró ninguna coincidencia. Funciona mejor con música comercial, Spotify, Apple Music o remixes de canciones de YouTube. Podrían no ser reconocidas.""",
    "timer" to """Temporizador""",
    "ok" to """Aceptar""",
    "auto_loudness" to """Modo auto loudness""",
    "presets" to """Ajustes preestablecidos""",
    "preset_custom" to """Personalizado""",
    "preset_normal" to """Normal""",
    "preset_classic" to """Classic""",
    "double_tap_edges" to """Toca dos veces los bordes para cambiar de canción""",
    "double_tap_here_skip" to """Toca dos veces aquí para adelantar o retrasar 10s""",
    "rotate_cover_to_seek" to """Gira la portada para adelantar o retrasar""",
    "playback_options" to """Opciones de Reproducción""",
    "dynamic_plus" to """Dinámico+""",
    "support_suggestions" to """Apoyo y Sugerencias""",
    "suggest_idea" to """Sugerir idea""",
    "send_feedback" to """Envía comentarios o sugerencias para nuevas funciones.""",
    "support_patreon" to """Apóyanos en Patreon y obtén nuevos estilos visuales y nuevos estilos visuales para ondas.""",
    "patreon_code" to """Código de Patreon""",
    "redeem_code" to """Canjear código""",
    "patreon_wall" to """Muro Patreon""",
    "checking_dependencies" to """Comprobando dependencias...""",
    "ffmpeg_required_desc" to """Para recortar audios en computadora, es necesario descargar FFmpeg (una librería segura de código abierto).""",
    "downloading_ffmpeg" to """Descargando e instalando FFmpeg...""",
    "download_ffmpeg_btn" to """Descargar FFmpeg""",
    "duration_unknown_note" to """Nota: No se pudo obtener la duración exacta.""",
    "trim_audio_anchor" to """Ancla actual: %1${'$'}s""",
    "trim_audio_start_btn" to """Inicio""",
    "trim_audio_play_anchor" to """Desde ancla""",
    "trim_audio_stop" to """Detener""",
    "trim_audio_minus_10s" to """-10s al fin""",
    "trim_audio_trim_btn" to """Recortar""",
    "trim_error_generic" to """Error al recortar el audio.""",
    "reset_defaults" to """Restablecer a valores por defecto"""
)

val desktopStringsEn = mapOf(
    "app_name" to """DuWave""",
    "swipe_to_choose" to """Swipe the mini-player sideways to switch sections!""",
    "perm_mic_denied" to """Rhythmic animations are disabled because there is no microphone permission.""",
    "perm_storage_denied" to """Storage permission is required to find your music.""",
    "add_to_playlist" to """Add to Playlist""",
    "no_playlists" to """You have no playlists created. Create one from the Albums tab.""",
    "added_to_playlist" to """Added to %1${'$'}s""",
    "close" to """Close""",
    "welcome_title" to """Welcome to DuWave!""",
    "welcome_body" to """👋 Main Gestures:\n\n• Swipe sideways on the mini-player to switch between Home, Library, and Player.\n\n• Use the magnifying glass in Library to search and the reload button to find new music.\n\n• Tap here to start listening.""",
    "tab_all" to """All""",
    "tab_browser" to """Browser""",
    "tab_recommendations" to """Recommendations""",
    "reload_local_music" to """Reload local music""",
    "search_local_music" to """Search local music...""",
    "search_recommendation" to """Search recommendation (e.g. artist)""",
    "today_recommendations" to """Today\'s Recommendations""",
    "recommendations_desc" to """Explore and discover music you might like based on your top tracks.""",
    "track_deleted" to """Track deleted""",
    "delete_from_library" to """Delete from library""",
    "more_options" to """More options""",
    "my_playlists" to """My Playlists""",
    "other_local_folders" to """Other local folders""",
    "tap_plus_to_add" to """Tap the + button to add a list.""",
    "no_tracks_found" to """No tracks found.""",
    "delete" to """Delete""",
    "no_folders_found" to """No folders with music found.""",
    "select_language" to """Select Language""",
    "language" to """Language""",
    "tab_albums" to """Albums""",
    "tab_playlists" to """Playlists""",
    "tab_folders" to """Folders""",
    "create_playlist" to """Create Playlist""",
    "playlist_name" to """Playlist Name""",
    "create" to """Create""",
    "visualizer_style" to """Visualizer Style""",
    "visualizer_bg" to """Dynamic Background""",
    "visualizer_sensitivity" to """Visual Sensitivity""",
    "visualizer_mode" to """Wave Mode""",
    "mode_3_band" to """Separated (Highs, Mids, Lows)""",
    "mode_1_band" to """Unified (All in one)""",
    "library" to """Library""",
    "searching_music" to """Searching music...""",
    "searching_recs" to """Searching recommendations based on your stats...""",
    "no_tracks_here" to """No tracks here.""",
    "no_results_online" to """No results found online.""",
    "refresh_recommendations" to """Updating soon...""",
    "sort_directory" to """Default directory""",
    "sort_title" to """Title A-Z""",
    "sort_artist" to """Artist A-Z""",
    "sort_album" to """Album A-Z""",
    "next_update_in_h_m" to """Next update in %1${'$'}dh %2${'$'}dm""",
    "updating_soon" to """Updating soon...""",
    "because_you_listened" to """Because you listened to %1${'$'}s""",
    "top_artists" to """Top Artists""",
    "trending_music" to """Trending Music""",
    "artist_based_on" to """Artist based on the track""",
    "show_whatsapp_audio" to """Show WhatsApp audios""",
    "hide_whatsapp_audio" to """Hide WhatsApp audios""",
    "scan_music_now" to """Scan music now""",
    "shape_squiggle" to """Squiggle shape""",
    "shape_square" to """Square shape""",
    "shape_circle" to """Circle shape""",
    "shape_rounded" to """Rounded shape""",
    "shape_prefix" to """Shape: """,
    "style_prefix" to """Style: """,
    "style_bars" to """Bars""",
    "style_circle" to """Circle""",
    "style_ring" to """Ring""",
    "style_waves" to """Waves""",
    "style_slime" to """Slime""",
    "style_bands" to """Bands""",
    "style_dots" to """Dots""",
    "style_particles" to """Particles""",
    "style_rings" to """Rings""",
    "style_aura" to """Aura""",
    "style_duwave" to """DuWave""",
    "tab_artists" to """Artists""",
    "playback_settings" to """Playback Settings""",
    "edit_tag" to """Edit Tag""",
    "eq_normal" to """Normal""",
    "eq_reverb" to """Reverb""",
    "eq_activate" to """activate""",
    "eq_deactivate" to """deactivate""",
    "equalizer" to """Equalizer""",
    "suggest_github" to """Suggest improvements on GitHub""",
    "delete_from_device" to """Delete from device""",
    "general_lists" to """General Lists""",
    "my_lists" to """My Lists""",
    "shuffle_playback" to """Shuffle Playback""",
    "repeat_method" to """Repeat Method""",
    "visualizer_style_opt" to """Visualizer Style""",
    "visualizer_physics" to """Visualizer Physics""",
    "bands_mode" to """Bands mode""",
    "speed_and_pitch" to """Speed and pitch""",
    "speed_format" to """Speed: %1${'$'}sx""",
    "pitch_format" to """Pitch: %1${'$'}sx""",
    "title" to """Title""",
    "artist" to """Artist""",
    "album" to """Album""",
    "save" to """Save""",
    "cancel" to """Cancel""",
    "enable_equalizer" to """Enable Equalizer""",
    "custom" to """Custom""",
    "your_statistics" to """Your Statistics""",
    "start_listening_stats" to """Start listening to music to see your stats here.""",
    "searching_recommendations" to """Searching recommendations based on your stats...""",
    "searching_online" to """Searching online...""",
    "search_lyrics" to """Lyrics""",
    "off" to """Off""",
    "repeat_list" to """List""",
    "repeat_one" to """One""",
    "repeat_ab" to """A & B""",
    "wave_archetype" to """Wave Archetype""",
    "waves_3_overlapping" to """3 Overlapping Waves""",
    "wave_1_combined" to """1 Combined Wave""",
    "calculation_mode_fft" to """Calculation Mode (FFT)""",
    "fft_average" to """Average (Stable)""",
    "fft_maximum" to """Maximum (Dynamic)""",
    "chaos_reactivity_format" to """Chaos Reactivity: %1${'$'}sx""",
    "bass_sensitivity_format" to """Bass Sensitivity: %1${'$'}sx""",
    "mid_sensitivity_format" to """Mid Sensitivity: %1${'$'}sx""",
    "treble_sensitivity_format" to """Treble Sensitivity: %1${'$'}sx""",
    "general_sensitivity_format" to """General Sensitivity: %1${'$'}sx""",
    "advanced_sensitivity" to """Advanced Sensitivity""",
    "choose_cover" to """Choose Cover""",
    "custom_cover_selected" to """Custom cover selected""",
    "audio_effects" to """Audio Effects""",
    "preset_effects" to """Preset (Effects)""",
    "slow_reverb" to """Slow Reverb""",
    "auto_mode_loudness" to """Auto Mode (Loudness)""",
    "preset_label" to """Preset:""",
    "sleep_timer" to """Sleep Timer""",
    "exact_timer" to """Exact Timer""",
    "turn_off" to """Turn Off""",
    "suggest_improvements" to """Suggest improvements""",
    "suggest_improvements_desc" to """Do you want to open the browser to suggest improvements or report issues on GitHub?""",
    "playback_queue" to """Playback Queue""",
    "accept" to """Accept""",
    "open" to """Open""",
    "no_playlists_long" to """You have no playlists created. Create one from the Albums tab.""",
    "no_playlists_short" to """You have no playlists created.""",
    "new_playlist" to """New Playlist""",
    "search_songs" to """Search songs...""",
    "add_songs" to """Add Songs""",
    "search_in_format" to """Search in %1${'$'}s...""",
    "delete_song_title" to """Delete song""",
    "delete_song_desc" to """Are you sure you want to permanently delete \'%1${'$'}s\' from the device?""",
    "confirm_download" to """Confirm download""",
    "confirm_download_desc" to """Do you want to download \'%1${'$'}s\' to your device to listen offline?""",
    "download" to """Download""",
    "remove_from_playlist" to """Remove from Playlist""",
    "download_music" to """Download music""",
    "trim_audio" to """Trim audio""",
    "save_trim" to """Save Trim""",
    "start_time" to """Start time: %1${'$'}s""",
    "end_time" to """End time: %1${'$'}s""",
    "trimming_audio" to """Trimming audio...""",
    "trim_saved_success" to """Trim saved successfully""",
    "trim_error" to """Error trimming audio""",
    "playback_progress" to """Progress: %1${'$'}s""",
    "confirm_link_download" to """Confirm link download""",
    "download_from_youtube_desc" to """Download \"%1${'$'}s\" from YouTube?""",
    "stats_title" to """Your Statistics""",
    "stats_no_data" to """No data yet!""",
    "stats_you_listened" to """You have listened to""",
    "stats_of_music" to """of music""",
    "stats_total_plays" to """%1${'$'}s total plays""",
    "stats_songs" to """Songs""",
    "stats_artists" to """Artists""",
    "stats_albums" to """Albums""",
    "stats_top_artists" to """Most Listened Artists""",
    "stats_top_songs" to """Most Listened Songs""",
    "stats_top_albums" to """Most Listened Albums""",
    "stats_your_favorites" to """Your Favorites""",
    "stats_plays_short" to """%1${'$'}s plays""",
    "based_on" to """Based on: %1${'$'}s""",
    "for_you" to """For you""",
    "search_dots" to """Search...""",
    "search_online_dots" to """Search online...""",
    "shape_squircle" to """Shape: Squircle""",
    "change_cover_title" to """Change Cover""",
    "style_classic" to """Style: Classic""",
    "style_cyberpunk" to """Style: Cyberpunk""",
    "style_anime" to """Style: Pastel Anime""",
    "style_luminous" to """Style: Luminous""",
    "style_kawaii" to """Style: Kawaii""",
    "style_black_metal" to """Style: Black Metal""",
    "style_dark_fantasy" to """Style: Dark Fantasy""",
    "style_cathedral" to """Style: Cathedral""",
    "style_hearts" to """Style: Hearts""",
    "style_tale_legend" to """Style: Fairy Tale""",
    "reload_covers" to """Reload Covers""",
    "reloading_covers_progress" to """Reloading %1${'$'}d of %2${'$'}d...""",
    "covers_reloaded" to """Covers reloaded""",
    "support_dialog_title" to """Support & Suggestions""",
    "support_ideas_title" to """Want to share ideas?""",
    "support_ideas_desc" to """Write them in the GitHub issues to improve the app.""",
    "support_patreon_title" to """Support the project""",
    "support_patreon_desc" to """Help it grow with more styles, wave types, and personal benefits.""",
    "gesture_next_prev" to """Double tap the edges to change track""",
    "gesture_seek_10s" to """Double tap here to seek 10s""",
    "gesture_vinyl_seek" to """Rotate the cover to seek""",
    "gesture_playlist_swipe" to """Swipe up to open playlist""",
    "gesture_confirmations_toggle" to """Visual gesture confirmations""",
    "download_completed" to """Download completed""",
    "download_completed_desc" to """Download completed: %1${'$'}s""",
    "player_options" to """Player Options""",
    "basic_options" to """Base Options""",
    "advanced_options" to """Advanced Options""",
    "visuals" to """Visuals""",
    "dynamic_plus" to """Dynamic Colors+""",
    "reset_defaults" to """Reset to defaults""",
    "enable_equalizer" to """Enable Equalizer""",
    "auto_loudness" to """Auto-Loudness Mode""",
    "presets" to """Presets""",
    "preset_custom" to """Custom""",
    "normal" to """Normal""",
    "trim_audio_anchor" to """Current anchor: %s""",
    "start_time" to """Start: %s""",
    "end_time" to """End: %s""",
    "trim_audio_start_btn" to """Start""",
    "trim_audio_play_anchor" to """From anchor""",
    "trim_audio_stop" to """Stop""",
    "trim_audio_minus_10s" to """-10s to end""",
    "trim_audio_trim_btn" to """Trim""",
    "trim_error_generic" to """Error trimming audio.""",
    "checking_dependencies" to """Checking dependencies...""",
    "ffmpeg_required_desc" to """FFmpeg is required.""",
    "downloading_ffmpeg" to """Downloading FFmpeg...""",
    "download_ffmpeg_btn" to """Download FFmpeg""",
    "duration_unknown_note" to """Unknown duration.""",
    "search_in_category" to """Search in %s...""",
    "folders_category" to """Folders""",
    "no_playlists_created" to """You have no playlists. Create one from the Albums tab.""",
    "delete_track_title" to """Delete track""",
    "delete_track_desc" to """Are you sure you want to permanently delete \'%1${'$'}s\' from your device?""",
    "delete_button_red" to """Delete""",
    "play_trimmed" to """Play Trim""",
    "pause_trimmed" to """Pause""",
    "stats_time_format" to """%1${'$'}d hours %2${'$'}d minutes""",
    "toast_fetching_link" to """Fetching link for %1${'$'}s...""",
    "toast_download_started" to """Download started: %1${'$'}s""",
    "toast_download_failed_link" to """Could not get link for %1${'$'}s""",
    "toast_download_error" to """Error processing download for %1${'$'}s""",
    "toast_downloading" to """Downloading %1${'$'}s...""",
    "all_songs_title" to """All Songs""",
    "recent_plays_title" to """Recently Played""",
    "favorites_title" to """Favorites""",
    "top_plays_title" to """Top Played""",
    "recently_added_title" to """Recently Added""",
    "playback_error" to """Error playing: File not found or corrupted.""",
    "online_service_down" to """The service is currently unavailable, please wait for a new update.""",
    "mic_test_title" to """Live Audio Test""",
    "mic_test_desc" to """This section is for testing your voice or live environment with DuWave visualizers. It requires microphone access to synchronize the waves, but it will not record or save audio.""",
    "clean_ui" to """Clean UI""",
    "move" to """Move""",
    "effects" to """Effects""",
    "normal" to """Normal""",
    "chroma" to """Chroma""",
    "hidden" to """Hidden""",
    "select_custom_cover" to """Select custom cover image""",
    "cover_size" to """Cover Size""",
    "exit_streamer_mode" to """Exit Streamer Mode""",
    "mic_bar" to """Mic Bar""",
    "cover_options" to """Cover Options""",
    "player_options" to """Player Options""",
    "basic_options" to """Basic""",
    "advanced_options" to """Advanced""",
    "visuals" to """Visuals""",
    "visual_waves" to """Visual Waves""",
    "archetypes" to """Archetypes""",
    "three_overlapping_waves" to """3 Overlapping Waves""",
    "one_combined_wave" to """One Combined Wave""",
    "general_sensitivity" to """General Sensitivity""",
    "fluidity" to """Fluidity""",
    "reactivity" to """Reactivity""",
    "visual_style" to """Visual Style""",
    "shazam_listening_desc" to """Bring the microphone closer to the music. Let it play for a few seconds...""",
    "waves" to """Waves""",
    "slime" to """Slime""",
    "bars" to """Bars""",
    "dots" to """Dots""",
    "particles" to """Particles""",
    "rings" to """Rings""",
    "aura" to """Aura""",
    "bands" to """Bands""",
    "terrain_3d" to """3D Terrain""",
    "star" to """Star""",
    "oscilloscope" to """Oscilloscope""",
    "trap_nation" to """Trap Nation""",
    "perspective_bands" to """Perspective Bands""",
    "archetype" to """Archetype""",
    "three_combined_waves" to """Three Combined Waves""",
    "frequency_sensitivity" to """Frequency Sensitivity""",
    "advanced" to """Advanced""",
    "bass" to """Bass""",
    "mids_treble" to """Mids & Treble""",
    "advanced_cover_options" to """Advanced Cover Options""",
    "cover_mode" to """Cover Mode""",
    "size" to """Size""",
    "cover_preview" to """Cover Preview""",
    "generated_palette" to """Generated Palette""",
    "apply" to """Apply""",
    "listening" to """Listening...""",
    "could_not_recognize" to """Could not recognize""",
    "no_match_found" to """No match found. Works best with commercial music, Spotify, Apple Music, or YouTube remixes. They might not be recognized.""",
    "timer" to """Timer""",
    "ok" to """OK""",
    "auto_loudness" to """Auto Loudness Mode""",
    "presets" to """Presets""",
    "preset_custom" to """Custom""",
    "preset_normal" to """Normal""",
    "preset_classic" to """Classic""",
    "double_tap_edges" to """Double tap edges to change song""",
    "double_tap_here_skip" to """Double tap here to skip or rewind 10s""",
    "rotate_cover_to_seek" to """Rotate cover to seek""",
    "playback_options" to """Playback Options""",
    "dynamic_plus" to """Dynamic+""",
    "support_suggestions" to """Support & Suggestions""",
    "suggest_idea" to """Suggest Idea""",
    "send_feedback" to """Send feedback or suggestions for new features.""",
    "support_patreon" to """Support us on Patreon and get new visual styles and new visual styles for waves.""",
    "patreon_code" to """Patreon Code""",
    "redeem_code" to """Redeem Code""",
    "patreon_wall" to """Patreon Wall""",
    "checking_dependencies" to """Checking dependencies...""",
    "ffmpeg_required_desc" to """To trim audio on computer, you need to download FFmpeg (a secure open-source library).""",
    "downloading_ffmpeg" to """Downloading and installing FFmpeg...""",
    "download_ffmpeg_btn" to """Download FFmpeg""",
    "duration_unknown_note" to """Note: Could not get exact duration.""",
    "trim_audio_anchor" to """Current anchor: %1${'$'}s""",
    "trim_audio_start_btn" to """Start""",
    "trim_audio_play_anchor" to """From anchor""",
    "trim_audio_stop" to """Stop""",
    "trim_audio_minus_10s" to """-10s to end""",
    "trim_audio_trim_btn" to """Trim""",
    "trim_error_generic" to """Error trimming audio.""",
    "reset_defaults" to """Reset to defaults"""
)

val desktopStringsPt = mapOf(
    "app_name" to """DuWave""",
    "swipe_to_choose" to """Deslize o mini-player para os lados para mudar de seção!""",
    "perm_mic_denied" to """As animações rítmicas estão desativadas porque não há permissão de microfone.""",
    "perm_storage_denied" to """A permissão de armazenamento é necessária para encontrar suas músicas.""",
    "add_to_playlist" to """Adicionar à Playlist""",
    "no_playlists" to """Você não tem playlists criadas. Crie uma na guia Álbuns.""",
    "added_to_playlist" to """Adicionado a %1${'$'}s""",
    "close" to """Fechar""",
    "welcome_title" to """Bem-vindo ao DuWave!""",
    "welcome_body" to """👋 Gestos Principais:\n\n• Deslize para os lados no mini-player para alternar entre Início, Biblioteca e Reprodutor.\n\n• Use a lupa na Biblioteca para pesquisar e o botão de recarregar para encontrar novas músicas.\n\n• Toque aqui para começar a ouvir.""",
    "tab_all" to """Todos""",
    "tab_browser" to """Navegador""",
    "tab_recommendations" to """Recomendações""",
    "reload_local_music" to """Recarregar músicas locais""",
    "search_local_music" to """Pesquisar música local...""",
    "search_recommendation" to """Pesquisar recomendação (ex: artista)""",
    "today_recommendations" to """Recomendações de Hoje""",
    "recommendations_desc" to """Explore e descubra músicas que você pode gostar com base nas mais ouvidas.""",
    "track_deleted" to """Música excluída""",
    "delete_from_library" to """Excluir da biblioteca""",
    "more_options" to """Mais opções""",
    "my_playlists" to """Minhas Playlists""",
    "other_local_folders" to """Outras pastas locais""",
    "tap_plus_to_add" to """Toque no botão + para adicionar uma lista.""",
    "no_tracks_found" to """Nenhuma música encontrada.""",
    "delete" to """Excluir""",
    "no_folders_found" to """Nenhuma pasta com música encontrada.""",
    "select_language" to """Selecionar Idioma""",
    "language" to """Idioma""",
    "tab_albums" to """Álbuns""",
    "tab_playlists" to """Playlists""",
    "tab_folders" to """Pastas""",
    "create_playlist" to """Criar Playlist""",
    "playlist_name" to """Nome da Playlist""",
    "create" to """Criar""",
    "visualizer_style" to """Estilo de Visualizador""",
    "visualizer_bg" to """Fundo Dinâmico""",
    "visualizer_sensitivity" to """Sensibilidade Visual""",
    "visualizer_mode" to """Modo de Onda""",
    "mode_3_band" to """Separadas (Altos, Médios, Baixos)""",
    "mode_1_band" to """Unificada (Tudo em um)""",
    "library" to """Biblioteca""",
    "searching_music" to """Buscando música...""",
    "searching_recs" to """Buscando recomendações baseadas em suas estatísticas...""",
    "no_tracks_here" to """Nenhuma música aqui.""",
    "no_results_online" to """Nenhum resultado encontrado online.""",
    "refresh_recommendations" to """Atualizando em breve...""",
    "sort_directory" to """Diretório padrão""",
    "sort_title" to """Título A-Z""",
    "sort_artist" to """Artista A-Z""",
    "sort_album" to """Álbum A-Z""",
    "next_update_in_h_m" to """Próxima atualização em %1${'$'}dh %2${'$'}dm""",
    "updating_soon" to """Atualizando em breve...""",
    "because_you_listened" to """Porque você ouviu %1${'$'}s""",
    "top_artists" to """Top Artistas""",
    "trending_music" to """Música em alta""",
    "artist_based_on" to """Artista baseado na música""",
    "show_whatsapp_audio" to """Mostrar áudios do WhatsApp""",
    "hide_whatsapp_audio" to """Ocultar áudios do WhatsApp""",
    "scan_music_now" to """Escanear músicas agora""",
    "shape_squiggle" to """Forma de rabisco""",
    "shape_square" to """Forma quadrada""",
    "shape_circle" to """Forma circular""",
    "shape_rounded" to """Forma arredondada""",
    "shape_prefix" to """Forma: """,
    "style_prefix" to """Estilo: """,
    "style_bars" to """Barras""",
    "style_circle" to """Círculo""",
    "style_ring" to """Anel""",
    "style_waves" to """Ondas""",
    "style_slime" to """Slime""",
    "style_bands" to """Bandas""",
    "style_dots" to """Pontos""",
    "style_particles" to """Partículas""",
    "style_rings" to """Anéis""",
    "style_aura" to """Aura""",
    "style_duwave" to """DuWave""",
    "tab_artists" to """Artistas""",
    "playback_settings" to """Configurações de Reprodução""",
    "edit_tag" to """Editar Tag""",
    "eq_normal" to """Normal""",
    "eq_reverb" to """Reverb""",
    "eq_activate" to """ativar""",
    "eq_deactivate" to """desativar""",
    "equalizer" to """Equalizador""",
    "suggest_github" to """Sugerir melhorias no GitHub""",
    "delete_from_device" to """Excluir do dispositivo""",
    "general_lists" to """Listas Gerais""",
    "my_lists" to """Minhas Listas""",
    "shuffle_playback" to """Reprodução Aleatória""",
    "repeat_method" to """Método de Repetição""",
    "visualizer_style_opt" to """Estilo de Visualização""",
    "visualizer_physics" to """Física do Visualizador""",
    "bands_mode" to """Modo de bandas""",
    "speed_and_pitch" to """Velocidade e tom""",
    "speed_format" to """Velocidade: %1${'$'}sx""",
    "pitch_format" to """Tom: %1${'$'}sx""",
    "title" to """Título""",
    "artist" to """Artista""",
    "album" to """Álbum""",
    "save" to """Salvar""",
    "cancel" to """Cancelar""",
    "enable_equalizer" to """Ativar Equalizador""",
    "custom" to """Personalizado""",
    "your_statistics" to """Suas Estatísticas""",
    "start_listening_stats" to """Comece a ouvir músicas para ver suas estatísticas aqui.""",
    "searching_recommendations" to """Buscando recomendações baseadas em suas estatísticas...""",
    "searching_online" to """Buscando online...""",
    "search_lyrics" to """Letras""",
    "off" to """Desligado""",
    "repeat_list" to """Lista""",
    "repeat_one" to """Uma""",
    "repeat_ab" to """A e B""",
    "wave_archetype" to """Arquétipo de Ondas""",
    "waves_3_overlapping" to """3 Ondas Sobrepostas""",
    "wave_1_combined" to """1 Onda Combinada""",
    "calculation_mode_fft" to """Modo de Cálculo (FFT)""",
    "fft_average" to """Média (Estável)""",
    "fft_maximum" to """Máximo (Dinâmico)""",
    "chaos_reactivity_format" to """Reatividade do Caos: %1${'$'}sx""",
    "bass_sensitivity_format" to """Sensibilidade de Graves: %1${'$'}sx""",
    "mid_sensitivity_format" to """Sensibilidade de Médios: %1${'$'}sx""",
    "treble_sensitivity_format" to """Sensibilidade de Agudos: %1${'$'}sx""",
    "general_sensitivity_format" to """Sensibilidade Geral: %1${'$'}sx""",
    "advanced_sensitivity" to """Sensibilidade Avançada""",
    "choose_cover" to """Escolher Capa""",
    "custom_cover_selected" to """Capa personalizada selecionada""",
    "audio_effects" to """Efeitos de Áudio""",
    "preset_effects" to """Predefinição (Efeitos)""",
    "slow_reverb" to """Slow Reverb""",
    "auto_mode_loudness" to """Modo Auto (Loudness)""",
    "preset_label" to """Preset:""",
    "sleep_timer" to """Temporizador""",
    "exact_timer" to """Temporizador Exato""",
    "turn_off" to """Desligar""",
    "suggest_improvements" to """Sugerir melhorias""",
    "suggest_improvements_desc" to """Deseja abrir o navegador para sugerir melhorias ou relatar problemas no GitHub?""",
    "playback_queue" to """Fila de Reprodução""",
    "accept" to """Aceitar""",
    "open" to """Abrir""",
    "no_playlists_long" to """Você não tem playlists criadas. Crie uma na guia Álbuns.""",
    "no_playlists_short" to """Você não tem playlists criadas.""",
    "new_playlist" to """Nova Playlist""",
    "search_songs" to """Buscar músicas...""",
    "add_songs" to """Adicionar Músicas""",
    "search_in_format" to """Buscar em %1${'$'}s...""",
    "delete_song_title" to """Excluir música""",
    "delete_song_desc" to """Tem certeza de que deseja excluir permanentemente \'%1${'$'}s\' do dispositivo?""",
    "confirm_download" to """Confirmar download""",
    "confirm_download_desc" to """Deseja baixar \'%1${'$'}s\' no seu dispositivo para ouvir offline?""",
    "download" to """Baixar""",
    "remove_from_playlist" to """Remover da Playlist""",
    "download_music" to """Baixar música""",
    "trim_audio" to """Cortar áudio""",
    "save_trim" to """Salvar Corte""",
    "start_time" to """Tempo de início: %1${'$'}s""",
    "end_time" to """Tempo final: %1${'$'}s""",
    "trimming_audio" to """Cortando áudio...""",
    "trim_saved_success" to """Corte salvo com sucesso""",
    "trim_error" to """Erro ao cortar áudio""",
    "playback_progress" to """Progresso: %1${'$'}s""",
    "confirm_link_download" to """Confirmar download do link""",
    "download_from_youtube_desc" to """Baixar \"%1${'$'}s\" do YouTube?""",
    "stats_title" to """Suas Estatísticas""",
    "stats_no_data" to """Sem dados ainda!""",
    "stats_you_listened" to """Você ouviu""",
    "stats_of_music" to """de música""",
    "stats_total_plays" to """%1${'$'}s reproduções totais""",
    "stats_songs" to """Músicas""",
    "stats_artists" to """Artistas""",
    "stats_albums" to """Álbuns""",
    "stats_top_artists" to """Artistas Mais Ouvidos""",
    "stats_top_songs" to """Músicas Mais Ouvidas""",
    "stats_top_albums" to """Álbuns Mais Ouvidos""",
    "stats_your_favorites" to """Seus Favoritos""",
    "stats_plays_short" to """%1${'$'}s rep.""",
    "based_on" to """Baseado em: %1${'$'}s""",
    "for_you" to """Para você""",
    "search_dots" to """Pesquisar...""",
    "search_online_dots" to """Pesquisar online...""",
    "shape_squircle" to """Forma: Squircle""",
    "change_cover_title" to """Alterar Capa""",
    "style_classic" to """Estilo: Clássico""",
    "style_cyberpunk" to """Estilo: Cyberpunk""",
    "style_anime" to """Estilo: Anime Pastel""",
    "style_luminous" to """Estilo: Luminoso""",
    "style_kawaii" to """Estilo: Kawaii""",
    "style_black_metal" to """Estilo: Black Metal""",
    "style_dark_fantasy" to """Estilo: Dark Fantasy""",
    "style_cathedral" to """Estilo: Catedral""",
    "style_hearts" to """Estilo: Corações""",
    "style_tale_legend" to """Estilo: Lenda e Conto""",
    "reload_covers" to """Recarregar Capas""",
    "reloading_covers_progress" to """Recarregando %1${'$'}d de %2${'$'}d...""",
    "covers_reloaded" to """Capas recarregadas""",
    "support_dialog_title" to """Apoio e Sugestões""",
    "support_ideas_title" to """Quer dar ideias?""",
    "support_ideas_desc" to """Escreva nas issues do GitHub para melhorar o aplicativo.""",
    "support_patreon_title" to """Apoie o projeto""",
    "support_patreon_desc" to """Ajude a crescer com mais estilos, tipos de onda e benefícios pessoais.""",
    "gesture_next_prev" to """Toque duas vezes nas bordas para mudar de música""",
    "gesture_seek_10s" to """Toque duas vezes aqui para avançar ou voltar 10s""",
    "gesture_vinyl_seek" to """Gire a capa para avançar ou voltar""",
    "gesture_playlist_swipe" to """Deslize para cima para abrir a lista""",
    "gesture_confirmations_toggle" to """Confirmações visuais de gestos""",
    "download_completed" to """Download concluído""",
    "download_completed_desc" to """Download concluído: %1${'$'}s""",
    "player_options" to """Opções do reprodutor""",
    "basic_options" to """Opções Básicas""",
    "advanced_options" to """Opções Avançadas""",
    "visuals" to """Aspecto Visual""",
    "dynamic_plus" to """Cores Dinâmicas+""",
    "reset_defaults" to """Redefinir para os padrões""",
    "enable_equalizer" to """Ativar equalizador""",
    "auto_loudness" to """Modo Auto-Loudness""",
    "presets" to """Predefinições""",
    "preset_custom" to """Personalizado""",
    "normal" to """Normal""",
    "trim_audio_anchor" to """Âncora atual: %s""",
    "start_time" to """Início: %s""",
    "end_time" to """Fim: %s""",
    "trim_audio_start_btn" to """Início""",
    "trim_audio_play_anchor" to """Da âncora""",
    "trim_audio_stop" to """Parar""",
    "trim_audio_minus_10s" to """-10s até o fim""",
    "trim_audio_trim_btn" to """Recortar""",
    "trim_error_generic" to """Erro ao recortar áudio.""",
    "checking_dependencies" to """Verificando dependências...""",
    "ffmpeg_required_desc" to """FFmpeg é necessário.""",
    "downloading_ffmpeg" to """Baixando FFmpeg...""",
    "download_ffmpeg_btn" to """Baixar FFmpeg""",
    "duration_unknown_note" to """Duração desconhecida.""",
    "search_in_category" to """Pesquisar em %s...""",
    "folders_category" to """Pastas""",
    "no_playlists_created" to """Você não tem playlists. Crie uma na guia Álbuns.""",
    "delete_track_title" to """Excluir música""",
    "delete_track_desc" to """Tem certeza de que deseja excluir permanentemente \'%1${'$'}s\' do dispositivo?""",
    "delete_button_red" to """Excluir""",
    "play_trimmed" to """Ouvir Corte""",
    "pause_trimmed" to """Pausar""",
    "stats_time_format" to """%1${'$'}d horas %2${'$'}d minutos""",
    "toast_fetching_link" to """Obtendo link de %1${'$'}s...""",
    "toast_download_started" to """Download iniciado: %1${'$'}s""",
    "toast_download_failed_link" to """Não foi possível obter o link de %1${'$'}s""",
    "toast_download_error" to """Erro ao processar download de %1${'$'}s""",
    "toast_downloading" to """Baixando %1${'$'}s...""",
    "all_songs_title" to """Todas as músicas""",
    "recent_plays_title" to """Reproduções Recentes""",
    "favorites_title" to """Favoritos""",
    "top_plays_title" to """Mais Tocadas""",
    "recently_added_title" to """Adicionadas Recentemente""",
    "playback_error" to """Erro ao reproduzir: Arquivo não encontrado ou corrompido.""",
    "online_service_down" to """O serviço está indisponível no momento, por favor, aguarde uma nova atualização.""",
    "mic_test_title" to """Teste de Áudio ao Vivo""",
    "mic_test_desc" to """Esta seção serve para testar sua voz ou ambiente ao vivo com os visualizadores do DuWave. Requer acesso ao microfone para sincronizar as ondas, mas não gravará nem salvará áudio.""",
    "clean_ui" to """UI Limpa""",
    "move" to """Mover""",
    "effects" to """Efeitos""",
    "normal" to """Normal""",
    "chroma" to """Chroma""",
    "hidden" to """Oculta""",
    "select_custom_cover" to """Selecionar imagem de capa personalizada""",
    "cover_size" to """Tamanho da Capa""",
    "exit_streamer_mode" to """Sair do modo Streamer""",
    "mic_bar" to """Barra do Microfone""",
    "cover_options" to """Opções de Capa""",
    "player_options" to """Opções de Reprodutor""",
    "basic_options" to """Básico""",
    "advanced_options" to """Avançado""",
    "visuals" to """Visuais""",
    "visual_waves" to """Ondas Visuais""",
    "archetypes" to """Arquétipos""",
    "three_overlapping_waves" to """3 Ondas sobrepostas""",
    "one_combined_wave" to """Uma Onda Combinada""",
    "general_sensitivity" to """Sensibilidade Geral""",
    "fluidity" to """Fluidez""",
    "reactivity" to """Reatividade""",
    "visual_style" to """Estilo Visual""",
    "shazam_listening_desc" to """Aproxime o microfone da música. Deixe tocar por alguns segundos...""",
    "waves" to """Ondas""",
    "slime" to """Slime""",
    "bars" to """Barras""",
    "dots" to """Pontos""",
    "particles" to """Partículas""",
    "rings" to """Anéis""",
    "aura" to """Aura""",
    "bands" to """Bandas""",
    "terrain_3d" to """Terreno 3D""",
    "star" to """Estrela""",
    "oscilloscope" to """Osciloscópio""",
    "trap_nation" to """Trap Nation""",
    "perspective_bands" to """Bandas com Perspectiva""",
    "archetype" to """Arquétipo""",
    "three_combined_waves" to """Três Ondas Combinadas""",
    "frequency_sensitivity" to """Sensibilidade por Frequência""",
    "advanced" to """Avançado""",
    "bass" to """Graves""",
    "mids_treble" to """Médios e Agudos""",
    "advanced_cover_options" to """Opções Avançadas de Capa""",
    "cover_mode" to """Modo de Capa""",
    "size" to """Tamanho""",
    "cover_preview" to """Pré-visualização da Capa""",
    "generated_palette" to """Paleta Gerada""",
    "apply" to """Aplicar""",
    "listening" to """Ouvindo...""",
    "could_not_recognize" to """Não foi possível reconhecer""",
    "no_match_found" to """Nenhuma correspondência encontrada. Funciona melhor com música comercial, Spotify, Apple Music ou remixes de músicas do YouTube. Podem não ser reconhecidas.""",
    "timer" to """Temporizador""",
    "ok" to """OK""",
    "auto_loudness" to """Modo Auto Loudness""",
    "presets" to """Predefinições""",
    "preset_custom" to """Personalizado""",
    "preset_normal" to """Normal""",
    "preset_classic" to """Clássico""",
    "double_tap_edges" to """Toque duas vezes nas bordas para mudar de música""",
    "double_tap_here_skip" to """Toque duas vezes aqui para avançar ou retroceder 10s""",
    "rotate_cover_to_seek" to """Gire a capa para avançar ou retroceder""",
    "playback_options" to """Opções de Reprodução""",
    "dynamic_plus" to """Dinâmico+""",
    "support_suggestions" to """Apoio e Sugestões""",
    "suggest_idea" to """Sugerir Ideia""",
    "send_feedback" to """Envie comentários ou sugestões para novos recursos.""",
    "support_patreon" to """Apoie-nos no Patreon e obtenha novos estilos visuais e novos estilos visuais para ondas.""",
    "patreon_code" to """Código do Patreon""",
    "redeem_code" to """Resgatar Código""",
    "patreon_wall" to """Mural Patreon""",
    "checking_dependencies" to """Verificando dependências...""",
    "ffmpeg_required_desc" to """Para cortar áudios no computador, é necessário baixar o FFmpeg (uma biblioteca segura de código aberto).""",
    "downloading_ffmpeg" to """Baixando e instalando o FFmpeg...""",
    "download_ffmpeg_btn" to """Baixar FFmpeg""",
    "duration_unknown_note" to """Nota: Não foi possível obter a duração exata.""",
    "trim_audio_anchor" to """Âncora atual: %1${'$'}s""",
    "trim_audio_start_btn" to """Início""",
    "trim_audio_play_anchor" to """Da âncora""",
    "trim_audio_stop" to """Parar""",
    "trim_audio_minus_10s" to """-10s para o fim""",
    "trim_audio_trim_btn" to """Cortar""",
    "trim_error_generic" to """Erro ao cortar o áudio.""",
    "reset_defaults" to """Redefinir para os padrões"""
)

